### ISSUE TITLE
Add support for Fabric v2.2

### ISSUE THREAD

**Issue by harisj-xlnx** [hyperledger-labs/fabric-machine#27]

**Comment by harisj-xlnx** [comment]
This involves the following steps:
- Fabric machine api
- Fabric machine protocol
- Integration with Fabric codebase
- Scripts to setup Fabric network, install/instantiate chaincode, create channel, join channel
- Smallbank benchmark

**Comment by maghbari** [comment]
Great Job..
Looking forward to test the 2.2 repo with my Alveo card and report test results..
Hope it will be out really soon since I want to migrate to HLF 2.x ASAP

**Comment by harisj-xlnx** [comment]
> Great Job.. Looking forward to test the 2.2 release with my Alveo card and report test results.. Hope it will be out really soon since I want to migrate to HLF 2.x ASAP

Thanks for your interest. The current timeline is end of June or early July for v2.2 because I am away on leave for the next 2 weeks. The code is already in v2.2 branch, but hasn't been fully merged into main branch and tested.

**Comment by harisj-xlnx** [comment]
This is now done so closing the issue.
